CREATE DATABASE cbo;
create table employees (id INT AUTO_INCREMENT,email VARCHAR(50) UNIQUE NOT NULL, name VARCHAR(40) NOT NULL, lastName VARCHAR(40),position VARCHAR(50), startDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id));


create table reports (id INT AUTO_INCREMENT,customerEmail VARCHAR(50) NOT NULL, customerName VARCHAR(40), employeeEmail VARCHAR(50), employeeName VARCHAR(40),data VARCHAR(1200), startDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id));

create table customers (id INT AUTO_INCREMENT,email VARCHAR(50) UNIQUE NOT NULL, name VARCHAR(40) NOT NULL, lastName VARCHAR(40), date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id));